name: moapp_project
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  table_calendar: ^3.1.1
  google_fonts: ^3.0.1
  youtube_data_api: ^1.0.4
  firebase_core: ^2.31.1
  shared_preferences: ^2.2.3
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.20.0
  google_sign_in: ^6.2.1
  flutter_inappwebview: ^6.0.0
  http: ^0.13.6
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  fonts:
    - family: Ribeye
      fonts:
        - asset: assets/fonts/Ribeye-Regular.ttf